package com.example.gymappdemo.ui.theme

import androidx.compose.ui.graphics.Color

// Default Light
val primaryLight_Default = Color(0xFF203443)
val onPrimaryLight_Default = Color(0xFFFFFFFF)
val secondaryLight_Default = Color(0xFF1A2738)
val onSecondaryLight_Default = Color(0xFFFFFFFF)
val tertiaryLight_Default = Color(0xFFFF4C29)
val onTertiaryLight_Default = Color(0xFFFFFFFF)
val backgroundLight_Default = Color(0xFFFBF9FA)
val onBackgroundLight_Default = Color(0xFF1B1C1D)
val surfaceLight_Default = Color(0xFFFBF9FA)
val onSurfaceLight_Default = Color(0xFF1B1B1D)
val errorLight_Default = Color(0xFFBA1A1A)
val onErrorLight_Default = Color(0xFFFFFFFF)
val customColor1Light_Default = Color(0xFF000B18)
val onCustomColor1Light_Default = Color(0xFFFFFFFF)

// Default Dark
val primaryDark_Default = Color(0xFFB4C9DB)
val onPrimaryDark_Default = Color(0xFF1E3341)
val secondaryDark_Default = Color(0xFFBAC7DE)
val onSecondaryDark_Default = Color(0xFF243143)
val tertiaryDark_Default = Color(0xFFCC3C21)
val onTertiaryDark_Default = Color(0xFFFFFFFF)
val backgroundDark_Default = Color(0xFF121314)
val onBackgroundDark_Default = Color(0xFFE3E2E3)
val surfaceDark_Default = Color(0xFF131315)
val onSurfaceDark_Default = Color(0xFFE4E2E3)
val errorDark_Default = Color(0xFFFFB4AB)
val onErrorDark_Default = Color(0xFF690005)
val customColor1Dark_Default = Color(0xFFB3C9E1)
val onCustomColor1Dark_Default = Color(0xFF1D3245)

// Blue Light
val primaryLight_Blue = Color(0xFF2196F3)
val onPrimaryLight_Blue = Color(0xFFFFFFFF)
val secondaryLight_Blue = Color(0xFF64B5F6)
val onSecondaryLight_Blue = Color(0xFFFFFFFF)
val tertiaryLight_Blue = Color(0xFFBBDEFB)
val onTertiaryLight_Blue = Color(0xFF000000)
val backgroundLight_Blue = Color(0xFFE3F2FD)
val onBackgroundLight_Blue = Color(0xFF0D47A1)
val surfaceLight_Blue = Color(0xFFFFFFFF)
val onSurfaceLight_Blue = Color(0xFF0D47A1)
val errorLight_Blue = Color(0xFFBA1A1A)
val onErrorLight_Blue = Color(0xFFFFFFFF)
val customColor1Light_Blue = Color(0xFF0D47A1)
val onCustomColor1Light_Blue = Color(0xFFFFFFFF)

// Blue Dark
val primaryDark_Blue = Color(0xFF90CAF9)
val onPrimaryDark_Blue = Color(0xFF0D47A1)
val secondaryDark_Blue = Color(0xFF64B5F6)
val onSecondaryDark_Blue = Color(0xFFFFFFFF)
val tertiaryDark_Blue = Color(0xFF42A5F5)
val onTertiaryDark_Blue = Color(0xFFFFFFFF)
val backgroundDark_Blue = Color(0xFF0D47A1)
val onBackgroundDark_Blue = Color(0xFF003457)
val surfaceDark_Blue = Color(0xFF1E88E5)
val onSurfaceDark_Blue = Color(0xFFE3F2FD)
val errorDark_Blue = Color(0xFFFFB4AB)
val onErrorDark_Blue = Color(0xFF690005)
val customColor1Dark_Blue = Color(0xFF1E88E5)
val onCustomColor1Dark_Blue = Color(0xFFFFFFFF)

// Green Light
val primaryLight_Green = Color(0xFF4CAF50)
val onPrimaryLight_Green = Color(0xFFFFFFFF)
val secondaryLight_Green = Color(0xFF81C784)
val onSecondaryLight_Green = Color(0xFFFFFFFF)
val tertiaryLight_Green = Color(0xFFA5D6A7)
val onTertiaryLight_Green = Color(0xFF000000)
val backgroundLight_Green = Color(0xFFE8F5E9)
val onBackgroundLight_Green = Color(0xFF1B5E20)
val surfaceLight_Green = Color(0xFFFFFFFF)
val onSurfaceLight_Green = Color(0xFF1B5E20)
val errorLight_Green = Color(0xFFBA1A1A)
val onErrorLight_Green = Color(0xFFFFFFFF)
val customColor1Light_Green = Color(0xFF1B5E20)
val onCustomColor1Light_Green = Color(0xFFFFFFFF)

// Green Dark
val primaryDark_Green = Color(0xFF81C784)
val onPrimaryDark_Green = Color(0xFF1B5E20)
val secondaryDark_Green = Color(0xFFA5D6A7)
val onSecondaryDark_Green = Color(0xFFFFFFFF)
val tertiaryDark_Green = Color(0xFF66BB6A)
val onTertiaryDark_Green = Color(0xFFFFFFFF)
val backgroundDark_Green = Color(0xFF1B5E20)
val onBackgroundDark_Green = Color(0xFFE8F5E9)
val surfaceDark_Green = Color(0xFF2E7D32)
val onSurfaceDark_Green = Color(0xFFE8F5E9)
val errorDark_Green = Color(0xFFFFB4AB)
val onErrorDark_Green = Color(0xFF690005)
val customColor1Dark_Green = Color(0xFF388E3C)
val onCustomColor1Dark_Green = Color(0xFFFFFFFF)

// Red Light
val primaryLight_Red = Color(0xFFF44336)
val onPrimaryLight_Red = Color(0xFFFFFFFF)
val secondaryLight_Red = Color(0xFFE57373)
val onSecondaryLight_Red = Color(0xFFFFFFFF)
val tertiaryLight_Red = Color(0xFFFFCDD2)
val onTertiaryLight_Red = Color(0xFF000000)
val backgroundLight_Red = Color(0xFFFFEBEE)
val onBackgroundLight_Red = Color(0xFFB71C1C)
val surfaceLight_Red = Color(0xFFFFFFFF)
val onSurfaceLight_Red = Color(0xFFB71C1C)
val errorLight_Red = Color(0xFFBA1A1A)
val onErrorLight_Red = Color(0xFFFFFFFF)
val customColor1Light_Red = Color(0xFFB71C1C)
val onCustomColor1Light_Red = Color(0xFFFFFFFF)

// Red Dark
val primaryDark_Red = Color(0xFFE57373)
val onPrimaryDark_Red = Color(0xFFB71C1C)
val secondaryDark_Red = Color(0xFFFFCDD2)
val onSecondaryDark_Red = Color(0xFFFFFFFF)
val tertiaryDark_Red = Color(0xFFF44336)
val onTertiaryDark_Red = Color(0xFFFFFFFF)
val backgroundDark_Red = Color(0xFFB71C1C)
val onBackgroundDark_Red = Color(0xFFFFEBEE)
val surfaceDark_Red = Color(0xFFB71C1C)
val onSurfaceDark_Red = Color(0xFFFFEBEE)
val errorDark_Red = Color(0xFFFFB4AB)
val onErrorDark_Red = Color(0xFF690005)
val customColor1Dark_Red = Color(0xFFCF6679)
val onCustomColor1Dark_Red = Color(0xFFFFFFFF)

// List of Custom Themes
val CustomThemes = listOf(
    AppThemeType.DEFAULT,
    AppThemeType.BLUE,
    AppThemeType.GREEN,
    AppThemeType.RED
)
